services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env

  app:
    container_name: api
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - postgres
